name: Deploy Web App to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      # 2. Debug directory structure
      - name: Debug Directory Structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing all directories:"
          ls -la
          echo "Git status:"
          git status
          echo "Git branch:"
          git branch
          echo "Git remote:"
          git remote -v
          echo "Finding all files:"
          find . -type f
          echo "Git log:"
          git log -1
          echo "Git show:"
          git show

      # 3. Cache npm dependencies.
      - name: Cache npm Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('main/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # 4. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 5. Install dependencies
      - name: Install Dependencies
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing all directories:"
          ls -la
          echo "Changing to main directory..."
          cd main
          echo "Current directory after cd: $(pwd)"
          echo "Listing main directory:"
          ls -la
          echo "Installing dependencies..."
          npm ci
          echo "Dependencies installed successfully"

      # 6. Clean and Build Production Server
      - name: Clean and Build Production Server
        run: |
          echo "Current directory: $(pwd)"
          echo "Changing to main directory..."
          cd main
          echo "Current directory after cd: $(pwd)"
          echo "Listing src directory:"
          ls -la src
          echo "Listing components directory:"
          ls -la src/components
          echo "Listing utility directory:"
          ls -la src/components/utility
          echo "Building project..."
          export NODE_OPTIONS="--max-old-space-size=4096"
          rm -rf dist
          npm run build
          echo "Build completed"

      # 7. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          audience: sts.amazonaws.com

      # 8. Deploy Static Assets to S3
      - name: Deploy Static Assets to S3
        run: |
          echo "Deploying static assets..."
          aws s3 sync ./main/dist/ s3://atpinvestment.com.bd/ \
            --exclude "index.html" \
            --cache-control "max-age=31536000, public" \
            --delete

      # 9. Deploy Index.html with No Cache
      - name: Deploy index.html to S3
        run: |
          echo "Deploying index.html..."
          aws s3 cp ./main/dist/index.html s3://atpinvestment.com.bd/index.html \
            --cache-control "max-age=0, no-cache, no-store, must-revalidate"

      # 10. Invalidate CloudFront Cache
      - name: Invalidate CloudFront Cache
        run: |
          echo "Invalidating CloudFront cache..."
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DISTRIBUTION_PROD_ID }} \
            --paths "/*"

